spring:
  profiles:
    active:
      - dev
---
server:
  port: 10000
spring:
  profiels: dev
  application:
    name: microservicecloud-config-client
eureka:
  client:
    server-url:
      defaultZone: http://eureka-dev.com:7001/eureka
---
server:
  port: 10001
spring:
  profiels: test
  application:
    name: microservicecloud-config-client
eureka:
  client:
    server-url:
      defaultZone: http://eureka-test.com:7001/eureka