spring:
  profiles:
    active:
      - dev
---
server:
  port: 10000
spring:
  profiels: dev
  application:
    name: springcloud-config-client
eureka:
  client:
    server-url:
      defaultZone: http://eureka1:11111/eureka/,http://eureka2:11112/eureka/
---
server:
  port: 10001
spring:
  profiels: test
  application:
    name: springcloud-config-client
eureka:
  client:
    server-url:
      defaultZone: http://eureka1:11111/eureka/,http://eureka2:11112/eureka/